Eyevinn/web-player

packages/demo/src/index.js
packages/demo/src/style.css
packages/demo/src/template.html

Creates a shareable url that contains the loaded manifest when clicked.

feat: add share button

---

packages/airplay/package-lock.json
packages/cast/package-lock.json
packages/core/package-lock.json
packages/eyevinn-skin/package-lock.json
packages/player/package-lock.json
packages/web-player-component/README.md
packages/web-player-component/package-lock.json
packages/web-player-component/package.json
packages/web-player-component/src/index.html
packages/web-player-component/src/index.js
packages/web-player-component/webpack.config.js

Added a Web Component for the web-player

feat: web-component

---

packages/demo/src/index.js

This PR replaces the example streams on demo page with live streams from us

Use Eyevinn test streams on demo page

---

packages/demo/src/index.js

Removed debug flag from PlayerAnalyticsConnector constructor

fix: removed debug flag from PlayerAnalyticsConnector constructor

---

packages/demo/package-lock.json
packages/demo/package.json
packages/demo/src/index.js

now, there are no errors, however there is a wierd bug that I think is related to the player (and de-init)
If I report stop on session x, the second event on event y (if I start it using the load button) is also stopped breaking all reporting on the forthcoming session.

feat: epas 0.3

---

packages/demo/package-lock.json
packages/demo/src/index.js
packages/demo/src/style.css
packages/demo/src/template.html

This PR addresses #45 and adds more example streams to the demo page. The following stream types are now available:
- HLS VOD
- MPEG-DASH VOD
- HLS LIVE
- MPEG-DASH LIVE
- HLS LIVE SSAI

feat: added more example streams: live and live ssai

---

packages/core/src/tech/ShakaTech.ts

fix: read seekable range from shaka when playing mpd

---

packages/core/src/WebPlayer.ts
packages/demo/src/index.js
packages/demo/src/style.css
packages/demo/src/template.html

feat: autoplay support

---

packages/web-player-component/src/index.html
packages/web-player-component/src/index.js

feat: autoplay visible support

---

packages/web-player-component/src/index.js

feat: pause autoplay visible videos when out of view

---

packages/demo/package-lock.json
packages/demo/package.json
packages/demo/src/index.js

fix: report metadata to analytics

---

packages/web-player-component/README.md
packages/web-player-component/package-lock.json
packages/web-player-component/package.json
packages/web-player-component/src/index.html
packages/web-player-component/src/index.js

This PR addresses #43 and adds support for EPAS tracking in web-component

feat: EPAS support in web-component

---

.github/workflows/test.yml
package.json
packages/core/jest.config.js
packages/core/package-lock.json
packages/core/package.json
packages/core/src/WebPlayer.test.ts
packages/core/src/util/contentType.test.ts
packages/core/tsconfig.json

This PR setup a foundation for unit testing, starting (but not limited to) with web-player core module

chore: a foundation for unit tests

---

.github/workflows/integration.yml
examples/index.html
examples/web-component/index.html
package-lock.json
package.json
playwright.config.ts
tests/web-component.spec.ts

This PR lays a foundation for integration and end-to-end tests using Playwright

chore: a foundation for integration / e2e tests

---

packages/core/src/tech/BaseTech.ts
packages/core/src/tech/DashJsTech.ts
packages/core/src/tech/HlsJsTech.ts
packages/core/src/tech/ShakaTech.ts
packages/eyevinn-skin/src/EyevinnSkin.tsx
packages/eyevinn-skin/src/components/buttons/textTrack/textTrack.module.css
packages/eyevinn-skin/src/components/buttons/textTrack/textTrackButton.tsx

fix: reset state on load

---

README.md
packages/web-player-component/README.md

This PR adds additional information for the main readme file, for example a list and description of the modules that can be used.

chore(docs): additions to readme

---

packages/demo/src/index.js
packages/eyevinn-skin/src/EyevinnSkin.tsx
packages/eyevinn-skin/src/components/buttons/audioTrack/audioTrack.module.css
packages/eyevinn-skin/src/components/buttons/textTrack/textTrack.module.css
packages/eyevinn-skin/src/components/buttons/textTrack/textTrackButton.tsx

This PR addresses some minor issues in the skin regarding subtitle track and audio track selection.

fix: subtitle and audio track selector

---

packages/demo/src/index.js
packages/demo/src/style.css
packages/demo/src/template.html

Changed CSS:
* Media queries change layout of buttons/checkbox
* Adjustments to CSS for buttons/checkbox
* Changed from toggling visibility to toggling display for snippet snackbar

fix: scaling on mobile displays

---

examples/chaos-proxy/index.html
examples/index.html
playwright.config.ts
tests/chaos-proxy.spec.ts

Had to set channel: 'chrome' in config to use media codecs; caused tests for Firefox and Webkit to stop working, so commented out those

feat: added Playwright e2e test using Chaos Stream Proxy

---

packages/airplay/package-lock.json
packages/cast/package-lock.json
packages/core/package-lock.json
packages/core/package.json
packages/core/src/util/contentType.ts
packages/demo/package-lock.json
packages/demo/src/index.js
packages/eyevinn-skin/package-lock.json
packages/player/package-lock.json
packages/web-player-component/package-lock.json

fix: correctly detect WHPP streams

---

.github/workflows/deploy_demo.yml
packages/core/README.md
packages/core/src/WebPlayer.ts
packages/core/src/util/contentType.ts
packages/demo/src/index.js
packages/demo/webpack.config.js

The "Cloudflare hack" should of course be optional...

fix: cloudflare 'hack' should be optional to enable

---

packages/player/README.md
packages/player/index.d.ts
packages/player/src/index.js

This PR adds API documentation for the web player SDK and also exposes the web player core options that one might want to set.

chore: improve web player documentation

---

packages/demo/src/index.js

Disable EPAS as the sink has been discontinued. Demo page throws a lot of errors at the moment so a new deploy of demo site should be done after this has been merged.

fix: removed discontinued epas sink
